# .travis.yml
dist: bionic

language: php

php:
  - 7.2

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit tests/app
